// Uncharted Expedition — seed data shared by the in-memory store and the
// MongoDB store (seeded once when both collections are empty).

import { FeedbackEntry, ExpeditionUser } from './models';

export const defaultUsers: ExpeditionUser[] = [
  {
    email: 'drake@uncharted.com',
    name: 'Nathan Drake',
    department: 'AI-DS',
    completedProducts: ['a1', 'a2', 'c1', 'c2', 'd1'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-1'],
    discoveredTreasures: ['tr-coin'],
  },
  {
    email: 'elena@press.org',
    name: 'Elena Fisher',
    department: 'COMPS',
    completedProducts: ['a1', 'c1', 'd1'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-2'],
    discoveredTreasures: ['tr-relic'],
  },
  {
    email: 'sully@treasure.net',
    name: 'Victor Sullivan',
    department: 'EXTC',
    completedProducts: ['a1', 'a2', 'c1'],
    unlockedLabs: ['a', 'c'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-c-2'],
    discoveredTreasures: ['tr-map'],
  },
  {
    email: 'chloe@expedition.io',
    name: 'Chloe Frazer',
    department: 'IT',
    completedProducts: ['a1', 'a2'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-1'],
    discoveredTreasures: ['tr-coin'],
  },
  {
    email: 'nadine@shoreline.sec',
    name: 'Nadine Ross',
    department: 'MECH',
    completedProducts: ['a1', 'c1'],
    unlockedLabs: ['a', 'c'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-2'],
    discoveredTreasures: [],
  },
  {
    email: 'sam@libertalia.org',
    name: 'Samuel Drake',
    department: 'AI-DS',
    completedProducts: ['a1'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'rafe@adlercorp.com',
    name: 'Rafe Adler',
    department: 'CIVIL',
    completedProducts: ['a1'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'cutter@history.org',
    name: 'Charlie Cutter',
    department: 'VLSI',
    completedProducts: ['a1'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'flynn@mercenary.org',
    name: 'Harry Flynn',
    department: 'EXTC',
    completedProducts: ['a1'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'tenzin@himalayas.net',
    name: 'Tenzin Sherpa',
    department: 'CIVIL',
    completedProducts: ['a1'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'marlowe@hermetic.co.uk',
    name: 'Katherine Marlowe',
    department: 'COMPS',
    completedProducts: ['a1'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'talbot@hermetic.co.uk',
    name: 'Talbot Hermetic',
    department: 'MECH',
    completedProducts: ['a1'],
    unlockedLabs: ['a'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
];

export const defaultFeedback: FeedbackEntry[] = [
  {
    _id: 'fb-1',
    studentName: 'Nathan Drake',
    studentEmail: 'drake@uncharted.com',
    studentDepartment: 'AI-DS',
    labId: 'a',
    tableId: 'a1',
    rating: 5,
    comment: 'Spectacular mountain discovery.',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    _id: 'fb-2',
    studentName: 'Nathan Drake',
    studentEmail: 'drake@uncharted.com',
    studentDepartment: 'AI-DS',
    labId: 'c',
    tableId: 'c1',
    rating: 5,
    comment: 'Found the ancient vault.',
    timestamp: new Date(Date.now() - 2600000).toISOString(),
    createdAt: new Date(Date.now() - 2600000),
  },
  {
    _id: 'fb-3',
    studentName: 'Elena Fisher',
    studentEmail: 'elena@press.org',
    studentDepartment: 'COMPS',
    labId: 'a',
    tableId: 'a1',
    rating: 5,
    comment: 'Rich history documented.',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    _id: 'fb-4',
    studentName: 'Victor Sullivan',
    studentEmail: 'sully@treasure.net',
    studentDepartment: 'EXTC',
    labId: 'a',
    tableId: 'a2',
    rating: 4,
    comment: 'Good haul of relics.',
    timestamp: new Date(Date.now() - 1400000).toISOString(),
    createdAt: new Date(Date.now() - 1400000),
  },
  {
    _id: 'fb-5',
    studentName: 'Chloe Frazer',
    studentEmail: 'chloe@expedition.io',
    studentDepartment: 'IT',
    labId: 'a',
    tableId: 'a1',
    rating: 4,
    comment: 'Interesting tech relics.',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    createdAt: new Date(Date.now() - 1200000),
  },
  {
    _id: 'fb-6',
    studentName: 'Nadine Ross',
    studentEmail: 'nadine@shoreline.sec',
    studentDepartment: 'MECH',
    labId: 'a',
    tableId: 'a2',
    rating: 4,
    comment: 'Rigorous expedition challenge.',
    timestamp: new Date(Date.now() - 1100000).toISOString(),
    createdAt: new Date(Date.now() - 1100000),
  },
  {
    _id: 'fb-7',
    studentName: 'Samuel Drake',
    studentEmail: 'sam@libertalia.org',
    studentDepartment: 'AI-DS',
    labId: 'a',
    tableId: 'a1',
    rating: 4,
    comment: 'Great clues everywhere.',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    createdAt: new Date(Date.now() - 900000),
  },
  {
    _id: 'fb-8',
    studentName: 'Rafe Adler',
    studentEmail: 'rafe@adlercorp.com',
    studentDepartment: 'CIVIL',
    labId: 'a',
    tableId: 'a1',
    rating: 3,
    comment: 'High ambition expedition.',
    timestamp: new Date(Date.now() - 800000).toISOString(),
    createdAt: new Date(Date.now() - 800000),
  },
  {
    _id: 'fb-9',
    studentName: 'Charlie Cutter',
    studentEmail: 'cutter@history.org',
    studentDepartment: 'VLSI',
    labId: 'a',
    tableId: 'a1',
    rating: 3,
    comment: 'Solid historical reference.',
    timestamp: new Date(Date.now() - 700000).toISOString(),
    createdAt: new Date(Date.now() - 700000),
  },
  {
    _id: 'fb-10',
    studentName: 'Harry Flynn',
    studentEmail: 'flynn@mercenary.org',
    studentDepartment: 'EXTC',
    labId: 'a',
    tableId: 'a1',
    rating: 3,
    comment: 'Found the entrance waypoint.',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    createdAt: new Date(Date.now() - 600000),
  },
  {
    _id: 'fb-11',
    studentName: 'Tenzin Sherpa',
    studentEmail: 'tenzin@himalayas.net',
    studentDepartment: 'CIVIL',
    labId: 'a',
    tableId: 'a1',
    rating: 3,
    comment: 'Guided path scouted.',
    timestamp: new Date(Date.now() - 500000).toISOString(),
    createdAt: new Date(Date.now() - 500000),
  },
  {
    _id: 'fb-12',
    studentName: 'Katherine Marlowe',
    studentEmail: 'marlowe@hermetic.co.uk',
    studentDepartment: 'COMPS',
    labId: 'a',
    tableId: 'a1',
    rating: 3,
    comment: 'Order and history examined.',
    timestamp: new Date(Date.now() - 400000).toISOString(),
    createdAt: new Date(Date.now() - 400000),
  },
  {
    _id: 'fb-13',
    studentName: 'Talbot Hermetic',
    studentEmail: 'talbot@hermetic.co.uk',
    studentDepartment: 'MECH',
    labId: 'a',
    tableId: 'a1',
    rating: 3,
    comment: 'Cipher decoded.',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    createdAt: new Date(Date.now() - 300000),
  },
];
